# Generated by Django 5.0.7 on 2024-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('year_of_graduation', models.IntegerField(verbose_name='Year of Graduation')),
                ('current_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Position')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni/', verbose_name='Alumni Photo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Facility Name')),
                ('description', models.TextField(verbose_name='Facility Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/', verbose_name='Facility Image')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='News Title')),
                ('content', models.TextField(verbose_name='News Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='News Image')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Student ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marks')),
                ('term', models.CharField(max_length=50, verbose_name='Term')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
    ]
