# Generated by Django 5.0.7 on 2024-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnyanjani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('file', models.FileField(upload_to='joining_instructions/', verbose_name='Joining Instruction File')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
        ),
    ]
