# Generated by Django 5.0.7 on 2024-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnyanjani', '0002_joininginstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='School Headmaster', max_length=100)),
                ('image', models.ImageField(upload_to='headmaster_photos/')),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
