# Generated by Django 5.0.7 on 2024-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnyanjani', '0003_headmaster_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Total')], max_length=1, verbose_name='Sex')),
                ('division_i', models.IntegerField(default=0, verbose_name='Division I Count')),
                ('division_ii', models.IntegerField(default=0, verbose_name='Division II Count')),
                ('division_iii', models.IntegerField(default=0, verbose_name='Division III Count')),
                ('division_iv', models.IntegerField(default=0, verbose_name='Division IV Count')),
                ('division_0', models.IntegerField(default=0, verbose_name='Division 0 Count')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Sex')),
                ('division', models.CharField(max_length=5, verbose_name='Division')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('detailed_subjects', models.TextField(verbose_name='Detailed Subjects')),
            ],
        ),
    ]
