# Generated by Django 5.0 on 2024-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mnyanjani", "0004_performanceoverview_studentresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Student Name")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("I", "Division I"),
                            ("II", "Division II"),
                            ("III", "Division III"),
                            ("IV", "Division IV"),
                            ("0", "Division 0"),
                        ],
                        max_length=3,
                        verbose_name="Division",
                    ),
                ),
                ("points", models.PositiveIntegerField(verbose_name="Points")),
                ("position", models.PositiveIntegerField(verbose_name="Position")),
                (
                    "detailed_subjects",
                    models.TextField(verbose_name="Detailed Subjects"),
                ),
            ],
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
            },
        ),
        migrations.CreateModel(
            name="SchoolPerformanceOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("T", "Total")],
                        max_length=1,
                        verbose_name="Sex",
                    ),
                ),
                ("division_i", models.PositiveIntegerField(verbose_name="Division I")),
                (
                    "division_ii",
                    models.PositiveIntegerField(verbose_name="Division II"),
                ),
                (
                    "division_iii",
                    models.PositiveIntegerField(verbose_name="Division III"),
                ),
                (
                    "division_iv",
                    models.PositiveIntegerField(verbose_name="Division IV"),
                ),
                ("division_0", models.PositiveIntegerField(verbose_name="Division 0")),
            ],
            options={
                "verbose_name": "School Performance Overview",
                "verbose_name_plural": "School Performance Overviews",
            },
        ),
        migrations.DeleteModel(
            name="PerformanceOverview",
        ),
        migrations.DeleteModel(
            name="Result",
        ),
        migrations.DeleteModel(
            name="StudentResult",
        ),
    ]
