# Generated by Django 5.0 on 2024-12-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mnyanjani", "0005_examresult_schoolperformanceoverview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="class_level",
            field=models.CharField(
                choices=[
                    ("Form 1", "Form 1"),
                    ("Form 2", "Form 2"),
                    ("Form 3", "Form 3"),
                    ("Form 4", "Form 4"),
                ],
                max_length=10,
                null=True,
                verbose_name="Class Level",
            ),
        ),
    ]
